name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/azure-static-web-apps-icy-meadow-062478d00.yml
      - public**
      - src**
      - .env
      - next.config.js
      - package-lock.json
      - package.json
      - tsconfig.json
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - .github/workflows/azure-static-web-apps-icy-meadow-062478d00.yml
      - public**
      - src**
      - .env
      - next.config.js
      - package-lock.json
      - package.json
      - tsconfig.json

jobs:
  build-deploy-swa:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Replace Secure Environment Variables
        run: |
          sed -i \
            -e 's|VALUE_OF_NEXT_PUBLIC_API_URI|${{ vars.API_URI }}|g' \
            -e 's|VALUE_OF_NEXT_PUBLIC_AZURE_AD_SP_MSAL_CLIENT_ID|${{ vars.AZURE_AD_SP_MSAL_CLIENT_ID }}|g' \
            -e 's|VALUE_OF_NEXT_PUBLIC_AZURE_TENANT_ID|${{ vars.AZURE_TENANT_ID }}|g' \
            .env

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          app_build_command: "npm run build"
          api_build_command: "rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          action: "close"
